
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pyc = 10;
  public static final int parc = 14;
  public static final int eval = 15;
  public static final int dosp = 30;
  public static final int cadena = 31;
  public static final int esta = 21;
  public static final int para = 13;
  public static final int coma = 4;
  public static final int graf = 22;
  public static final int tity = 27;
  public static final int titx = 26;
  public static final int por = 5;
  public static final int tit = 23;
  public static final int menos = 9;
  public static final int ejex = 24;
  public static final int pie = 28;
  public static final int digito = 16;
  public static final int div = 7;
  public static final int igual = 17;
  public static final int EOF = 0;
  public static final int id = 6;
  public static final int dou = 3;
  public static final int str = 8;
  public static final int error = 1;
  public static final int glob = 20;
  public static final int corc = 12;
  public static final int llavec = 19;
  public static final int mas = 2;
  public static final int cora = 11;
  public static final int llavea = 18;
  public static final int arch = 29;
  public static final int val = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "dou",
  "coma",
  "por",
  "id",
  "div",
  "str",
  "menos",
  "pyc",
  "cora",
  "corc",
  "para",
  "parc",
  "eval",
  "digito",
  "igual",
  "llavea",
  "llavec",
  "glob",
  "esta",
  "graf",
  "tit",
  "ejex",
  "val",
  "titx",
  "tity",
  "pie",
  "arch",
  "dosp",
  "cadena"
  };
}

