
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolosjs {
  /* terminals */
  public static final int modu = 45;
  public static final int dif = 36;
  public static final int consi = 32;
  public static final int du = 30;
  public static final int whi = 29;
  public static final int coma = 4;
  public static final int pote = 44;
  public static final int igual = 18;
  public static final int elsi = 27;
  public static final int llavec = 20;
  public static final int llavea = 19;
  public static final int bre = 33;
  public static final int iguall = 35;
  public static final int clase = 22;
  public static final int menos = 9;
  public static final int menor = 37;
  public static final int ife = 26;
  public static final int EOF = 0;
  public static final int dosp = 21;
  public static final int pyc = 10;
  public static final int parc = 17;
  public static final int mas = 2;
  public static final int para = 16;
  public static final int error = 1;
  public static final int menig = 38;
  public static final int corc = 13;
  public static final int fory = 28;
  public static final int mayor = 39;
  public static final int cora = 12;
  public static final int or = 42;
  public static final int por = 5;
  public static final int mayig = 40;
  public static final int str = 8;
  public static final int conste = 25;
  public static final int req = 34;
  public static final int id = 6;
  public static final int lete = 24;
  public static final int swi = 31;
  public static final int not = 43;
  public static final int and = 41;
  public static final int div = 7;
  public static final int vare = 23;
  public static final int deci = 11;
  public static final int dou = 3;
  public static final int digito = 14;
  public static final int cadena = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "dou",
  "coma",
  "por",
  "id",
  "div",
  "str",
  "menos",
  "pyc",
  "deci",
  "cora",
  "corc",
  "digito",
  "cadena",
  "para",
  "parc",
  "igual",
  "llavea",
  "llavec",
  "dosp",
  "clase",
  "vare",
  "lete",
  "conste",
  "ife",
  "elsi",
  "fory",
  "whi",
  "du",
  "swi",
  "consi",
  "bre",
  "req",
  "iguall",
  "dif",
  "menor",
  "menig",
  "mayor",
  "mayig",
  "and",
  "or",
  "not",
  "pote",
  "modu"
  };
}

