
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos_FCA {
  /* terminals */
  public static final int comp = 9;
  public static final int tit = 25;
  public static final int coma = 2;
  public static final int igual = 12;
  public static final int arch = 31;
  public static final int esta = 23;
  public static final int llavec = 4;
  public static final int tity = 29;
  public static final int titx = 28;
  public static final int llavea = 3;
  public static final int graf = 24;
  public static final int menos = 15;
  public static final int EOF = 0;
  public static final int dosp = 11;
  public static final int parc = 6;
  public static final int pyc = 7;
  public static final int mas = 14;
  public static final int glob = 22;
  public static final int para = 5;
  public static final int error = 1;
  public static final int val = 27;
  public static final int corc = 19;
  public static final int cora = 18;
  public static final int pesp = 20;
  public static final int por = 16;
  public static final int str = 35;
  public static final int id = 32;
  public static final int pie = 30;
  public static final int gre = 8;
  public static final int div = 17;
  public static final int dola = 21;
  public static final int deci = 33;
  public static final int dou = 34;
  public static final int ejex = 26;
  public static final int digito = 13;
  public static final int cadena = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "llavea",
  "llavec",
  "para",
  "parc",
  "pyc",
  "gre",
  "comp",
  "cadena",
  "dosp",
  "igual",
  "digito",
  "mas",
  "menos",
  "por",
  "div",
  "cora",
  "corc",
  "pesp",
  "dola",
  "glob",
  "esta",
  "graf",
  "tit",
  "ejex",
  "val",
  "titx",
  "tity",
  "pie",
  "arch",
  "id",
  "deci",
  "dou",
  "str"
  };
}

