
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos_FCA {
  /* terminals */
  public static final int pyc = 7;
  public static final int parc = 6;
  public static final int dosp = 11;
  public static final int para = 5;
  public static final int cadena = 10;
  public static final int coma = 2;
  public static final int por = 15;
  public static final int llavc = 4;
  public static final int menos = 14;
  public static final int llava = 3;
  public static final int div = 16;
  public static final int igual = 12;
  public static final int EOF = 0;
  public static final int gre = 8;
  public static final int error = 1;
  public static final int corc = 18;
  public static final int mas = 13;
  public static final int comp = 9;
  public static final int cora = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "llava",
  "llavc",
  "para",
  "parc",
  "pyc",
  "gre",
  "comp",
  "cadena",
  "dosp",
  "igual",
  "mas",
  "menos",
  "por",
  "div",
  "cora",
  "corc"
  };
}

